---
- name: Install theme x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ theming_theme_packages | combine(x_packages.theming | default({}), recursive=True) }}"

- name: Render gtk-3.0 settings
  ansible.builtin.template:
    src: gtk-3.0.settings.ini.j2
    dest: "/home/{{ x_target_user }}/.config/gtk-3.0/settings.ini"
    mode: "0644"
  become: true
  become_user: "{{ x_target_user }}"

- name: Render qt5ct rc
  ansible.builtin.template:
    src: qt5ct.conf.j2
    dest: "/home/{{ x_target_user }}/.config/qt5ct/qt5ct.conf"
    mode: "0644"
  become: true
  become_user: "{{ x_target_user }}"

- name: Stow theme config
  ansible.builtin.command: "stow -R theming"
  args:
    chdir: "/home/{{ x_target_user }}/dotfiles"
    creates: "/home/{{ x_target_user }}/.config/theme"
  become: true
  become_user: "{{ x_target_user }}"
