---
- name: Install component x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ x_packages.component_launcher }}"

- name: Stow component config
  ansible.builtin.command: "stow -R rofi"
  args:
    chdir: "/home/{{ x_target_user }}/dotfiles"
    creates: "/home/{{ x_target_user }}/.config/rofi"
  become: true
  become_user: "{{ x_target_user }}"
