---
- name: Install app x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ x_packages.app_neovim }}"

- name: Stow nvim config
  ansible.builtin.command: "stow -R {{ item }}"
  args:
    chdir: "/home/{{ x_target_user }}/dotfiles"
    creates: "/home/{{ x_target_user }}/.config/{{ item }}"
  become: true
  become_user: "{{ x_target_user }}"
  loop: "{{ app_neovim_nvim_stow_packages | combine((app_params | default({})).stow | default([])) }}"
  loop_control:
    label: "{{ item }}"
