---
- name: Install app packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    package_source: "{{ packages.app_neovim }}"

- name: Stow nvim config
  ansible.builtin.command: "stow -R {{ item }}"
  args:
    chdir: "/home/{{ target_user }}/dotfiles"
    creates: "/home/{{ target_user }}/.config/{{ item }}"
  become: true
  become_user: "{{ target_user }}"
  loop: "{{ nvim_stow_packages | combine((app_params | default({}).stow) | default([])) }}"
  loop_control:
    label: "{{ item }}"
