all:
  children:
    arch:
      hosts:
        thispc:
          ansible_connection: local
          target_disk: /dev/nvme0n1
          x_target_user: arito
          hostname: arito-pc
          timezone: Asia/Kolkata
          locale: en_US.UTF-8
          keymap: us
          partitions:
            - {size: 1G, type: efi, label: ESP}
            - {size: 8G, type: swap, label: swap}
            - {size: 100%, type: ext4, label: root}
          dotfiles_repo: git@github.com:aritro/dotfiles.git
          wm_choice: hyprland
          gpu_variant: nvidia_open
          audio_variant: pipewire
          snapshot_variant: ~
          aur_variant: yay
          desktop_hyprland_overrides: {}
          modules:
            development:
              vscode: {}
              docker: ~
            ai:
              llamacpp:
                cmake_flags:
                  - -DCMAKE_BUILD_TYPE=Release
                  - -DGGML_CUDA=ON
                  - -DCMAKE_CUDA_ARCHITECTURES=89
                  - -DGGML_CUDA_FA_ALL_QUANTS=ON
                  - -DGGML_CUDA_F16=ON
                  - -DGGML_NATIVE=ON
                  - -DGGML_AVX512=ON
                  - -DGGML_AVX512_VBMI=ON
                  - -DGGML_AVX512_VNNI=ON
                  - -DGGML_AVX512_BF16=ON
              opencode: {}
