all:
  children:
    arch:
      hosts:
        thispc:
          ansible_connection: local
          target_disk: /dev/nvme0n1
          x_target_user: arito
          hostname: arito-pc
          timezone: Asia/Kolkata
          locale: en_US.UTF-8
          keymap: us
          partitions:
            - {size: 1G, type: efi, label: ESP}
            - {size: 8G, type: swap, label: swap}
            - {size: 100%, type: ext4, label: root}
          dotfiles_repo: git@github.com:aritro/dotfiles.git
          wm_choice: hyprland
          gpu_variant: nvidia_open
          audio_variant: pipewire
          snapshot_variant: ~
          desktop_hyprland_overrides: {}
          modules:
            development:
              vscode: {}
              docker: ~
            ai:
              llamacpp: {}
              opencode: {}
