---
- name: Install component x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ x_packages.component_lock }}"

- name: Stow component config
  ansible.builtin.command: "stow -R hyprlock"
  args:
    chdir: "/home/{{ x_target_user }}/dotfiles"
    creates: "/home/{{ x_target_user }}/.config/hyprlock"
  become: true
  become_user: "{{ x_target_user }}"

- name: Enable lock user unit (never start)
  ansible.builtin.systemd:
    name: hyprlock.service
    scope: user
    enabled: true
    state: stopped
  become: true
  become_user: "{{ x_target_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_create_target_uid.pw.uid }}"
