---
- name: Install firewall x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ x_packages.firewall }}"

- name: Allow SSH on the default zone
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
  register: firewall_ufw_ssh
  failed_when: false

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: deny
  when: firewall_ufw_ssh is success
  register: firewall_ufw_enable
  failed_when: false
