---
- name: Install network x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ x_packages.network }}"

- name: Enable NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Enable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    state: started
