---
# Toolchains are an inventory dict:
#   lang_toolchains:
#     golang: {package: golang}
#     rust: {package: rust}
toolchain_defaults: {}
toolchains: "{{ toolchain_defaults | combine(app_params | default({})) }}"
