---
# Toolchains are an inventory dict:
#   lang_toolchains:
#     golang: {package: golang}
#     rust: {package: rust}
app_lang_toolchains_toolchain_defaults: {}
app_lang_toolchains_toolchains: "{{ app_lang_toolchains_toolchain_defaults | combine(app_params | default({})) }}"
