---
- name: Install component packages
  ansible.builtin.include_role:
    name: install_packages
    vars:
      package_source: "{{ packages.component_clipboard }}"

- name: Stow component config
  ansible.builtin.command: "stow -R clipboard"
  args:
    chdir: "/home/{{ target_user }}/dotfiles"
    creates: "/home/{{ target_user }}/.config/clipboard"
  become_user: "{{ target_user }}"
