---
- name: Install app x_packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_source: "{{ x_packages.app_git }}"

- name: Render .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ x_target_user }}/.gitconfig"
    mode: "0600"
  become: true
  become_user: "{{ x_target_user }}"
  when:
    - app_git_config.user_name | length > 0
    - app_git_config.user_email | length > 0
