---
- name: Install AUR x_packages via {{ x_commands.aur.install }}
  ansible.builtin.command: "{{ x_commands.aur.install }} -S --needsys --noconfirm {{ pkg_list | join(' ') }}"
  become: true
  become_user: "{{ x_target_user }}"
  register: install_packages_aur_rc
  changed_when: "'there is nothing to do' not in (install_packages_aur_rc.stdout | default(''))"
